[versions]
agp = "8.1.4"
kotlin = "1.8.10"
androidx-appcompat = "1.6.1"
androidx-multidex = "2.0.1"
google-services = "20.7.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "androidx-multidex" }
google-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "google-services" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }